### ISSUE TITLE
custom zmq port for litecoin

### ISSUE THREAD

**Issue by web3dopamine** [graphsense/ltc-client#1]
hi 
I have been trying a lot to get a custom port for litecoin but not able to

this is my docker-compose
```
version: "3.5"

services:

  litecoin-client:
    image: litecoin
    container_name: litecoin
    network_mode: "container:gluetun"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: /mnt/data/litecoin/data
        target: /opt/graphsense/data
      - type: bind
        source: /mnt/data/litecoin/docker/litecoin.conf
        target: /opt/graphsense/litecoin.conf
    restart: always
```

this is my litecoin.conf

```
server=1
# By default, only RPC connections from localhost are allowed.
# Specify as many rpcallowip= settings as you like to allow connections from other hosts,
# either as a single IPv4/IPv6 or with a subnet specification.
rpcbind=0.0.0.0:7232
port=7432
rpcallowip=0.0.0.0/0
txindex=1
disablewallet=1

rpcuser=user
rpcpassword=pass
rpcworkqueue=512
rpcthreads=4
dbcache=2500

zmqpubrawtx=tcp://0.0.0.0:58332
zmqpubrawblock=tcp://0.0.0.0:58332
zmqpubhashtx=tcp://0.0.0.0:58332
zmqpubhashblock=tcp://0.0.0.0:58332
```
whatever i do, by default it takes 28332 port, i am already running BTC which is taking 28332 port and that is why i need another port for litecoin

also is there a way to check on which port ZMQ is running for litecoin?
